config/routes.rb
Rails.application.routes.draw do
    devise_for :users

    resources :chat_rooms, only: [:new, :create, :show, :index]
    resources :private_chat_rooms, only: [:new, :create, :show, :index]
    resources :connections, only: [:new, :create, :show, :edit, :update, :index]

    mount ActionCable.server => '/cable'

    root 'chat_rooms#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
end

app/models/connection.rb
class Connection < ApplicationRecord
    belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
    belongs_to :chat_room
    validates :body, presence: true, length: {minimum: 2, maximum: 1000}
    after_create_commit { MessageBroadcastJob.perform_later(self) }
    def timestamp
        created_at.strftime('%H:%M:%S %d %B %Y')
    end
end

app/models/private_chat_room.rb
class PrivateChatRoom < ApplicationRecord
    belongs_to :user
    has_many :private_messages, dependent: :destroy
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
    belongs_to :user
    belongs_to :private_chat_room
    validates :body, presence: true, length: {minimum: 2, maximum: 1000}
    after_create_commit { PrivateMessageBroadcastJob.perform_later(self) }
    def timestamp
        created_at.strftime('%H:%M:%S %d %B %Y')
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :chat_rooms, dependent: :destroy
    has_many :messages, dependent: :destroy
    has_many :private_chat_rooms, dependent: :destroy
    has_many :private_messages, dependent: :destroy
    has_many :connections, dependent: :destroy
    # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    def name
        email.split('@')[0]
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    before_action :authenticate_user!
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
    def index
        @chat_rooms = ChatRoom.all
        @users = User.all
        @connection = Connection.new
        @connections = Connection.where(other_user_id: current_user.id, status: "pending")
        @requests = Connection.where(user_id: current_user.id, status: "pending")
        @private_chat_room = PrivateChatRoom.new
        @private_chat_rooms = PrivateChatRoom.all
    end

    def new
        @chat_room = ChatRoom.new
    end

    def create
        @chat_room = current_user.chat_rooms.build(chat_room_params)
        if @chat_room.save
            flash[:success] = 'Chat room added!'
            redirect_to chat_rooms_path
        else
            render 'new'
        end
    end

    def show
        @chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
        @message = Message.new
    end

    private

    def chat_room_params
        params.require(:chat_room).permit(:title)
    end
end

app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_connection, only: [:show, :edit, :update, :destroy]

    def new
        @connection = Connection.new
        @private_chat_room = PrivateChatRoom.new
    end

    def create
        @connection = Connection.create(connection_params)
        if @connection.save
            @user = User.find(@connection[:other_user_id])
            flash[:notice] = "#{@user.name} was requested"
            redirect_to(chat_rooms_path)
        else
            render('new')
        end
    end

    def edit

    end

    def update
        @connection.update_attributes(connection_params)
        if @connection.status == "accept"
            userOne = User.find_by(id: @connection.user_id)
            userTwo = User.find_by(id: @connection.other_user_id)
            @private_chat_room = PrivateChatRoom.create(user_id: userOne.id, other_user_id: userTwo.id, title: "#{userOne.name} - #{userTwo.name}")
        end
        redirect_to(private_chat_rooms_path)
    end

    def delete
    end

    def destroy
        @connection.destroy
        flash[:notice] = "Connection was rejected"
        redirect_to(chat_rooms_path)
    end

    private
        def set_connection
            @connection = Connection.find(params[:id])
        end
        def connection_params
            params.require(:connection).permit(:user_id, :other_user_id, :status)
        end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/controllers/private_chat_rooms_controller.rb
class PrivateChatRoomsController < ApplicationController
    def index
        @users = User.all
        @connections = Connection.where(other_user_id: current_user.id, status: "accept")
        @private_chat_rooms = PrivateChatRoom.where(user_id: current_user.id).or(PrivateChatRoom.where(other_user_id: current_user.id))

    end

    def new
        @private_chat_room = PrivateChatRoom.new
    end

    def create
        @private_chat_room = current_user.private_chat_rooms.build(private_chat_room_params)
        if @private_chat_room.save
            flash[:success] = 'Private chat room added!'
            redirect_to private_chat_rooms_path
        else
            render 'new'
        end
    end

    def show
        @private_chat_room = PrivateChatRoom.includes(:private_messages).find_by(id: params[:id])
        @private_message = PrivateMessage.new
    end

    private

    def private_chat_room_params
        params.require(:private_chat_room).permit(:title, :other_user_id)
    end
end

app/controllers/private_messages_controller.rb
class PrivateMessagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper

    def gravatar_for(user, opts = {})
        opts[:alt] = user.name
        image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}?s=#{opts.delete(:size) { 40 }}", opts
    end

    def can_see?(private_chat_room)
        current_user.id == private_chat_room.user_id || current_user.id == private_chat_room.other_user_id
    end
end

app/views/chat_rooms/_chat_room.html.erb
<tr>
    <td><%= link_to "#{chat_room.title}", chat_room_path(chat_room) %></td>
</tr>

app/views/chat_rooms/index.html.erb
<div class="main">
    <h6>Welcome, <%= current_user.name %></h6>
    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
    <div class="jumbotron">
        <div class="col-sm-4">
            <h4><%= link_to "Private Chats", private_chat_rooms_path %></h4>

        </div>
        <div class="col-sm-6">
            <h5>Requests</h5>
            <table>
                <% @connections.each do |connection| %>
                <tr>
                    <% name = User.find(connection.user_id).name %>
                    <td><%= name %></td>
                        <td><%= bootstrap_form_for(connection) do |f| %>
                            <%= f.select :status, ["accept", "reject"] %>
                            <%= f.hidden_field :user_id, :value => connection.user_id %>
                            <%= f.hidden_field :other_user_id, :value => current_user.id %>
                            <%= f.submit "Submit" %>
                        <% end %>
                    </td>
                </tr>
                <% end %>
            </table>
        </div>

        <div class="col-sm-6">
            <h5>Requested</h5>
            <table>
                <% @requests.each do |request| %>
                <tr>
                    <% name = User.find(request.other_user_id).name %>
                    <td><%= name %></td>
                    <td><%= request.status %></td>
                </tr>
            </table>
            <% end %>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-4">
            <h6>Start a conversation</h6>
            <%= bootstrap_form_for(@connection) do |f| %>
                <%= f.collection_select :other_user_id, @users, :id, :name, prompt: true %>
                <%= f.hidden_field :user_id, :value => current_user.id %>
                <%= f.hidden_field :status, :value => "pending" %>
                <div class="form-buttons">
                    <%= f.submit "Request User" %>
                </div>
            <% end %>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <h4>Question Board</h4>

            <p class="lead"><%= link_to 'Ask New Question', new_chat_room_path, class: 'btn btn-primary' %> </p>

            <table>
                <%= render @chat_rooms %>
            </table>
        </div>

    </div>

</div>

app/views/chat_rooms/new.html.erb
<h1>Ask New Question</h1>

<%= form_for @chat_room do |f| %>
    <div class="form-group">
        <%= f.text_field :title, autofocus: true, class: 'form-control' %>
    </div>

    <%= f.submit "Ask!", class: 'btn btn-primary' %>
<% end %>

app/views/chat_rooms/show.html.erb
<%= link_to "Back to Home", chat_rooms_path %>

<h1><%= @chat_room.title %></h1>

<div id="messages" data-chat-room-id="<%= @chat_room.id %>">
    <%= render @chat_room.messages %>
</div>

<hr>

<%= form_for @message, url: '#' do |f| %>
    <%= hidden_field_tag 'chat_room_id', @chat_room.id %>
    <div class="form-group">
        <%= f.text_area :body, class: 'form-control' %>
        <small class="text-muted">From 2 to 1000 characters</small>
  </div>

  <%= f.submit "Post", class: 'btn btn-primary btn-lg' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>CableChat</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
        <%= yield %>
    </body>
</html>

app/views/messages/_message.html.erb
<div class="card">
    <div class="card-block">
        <div class="row">
            <div class="col-md-1">
                <%= gravatar_for message.user %>
            </div>
            <div class="col-md-11">
                <p class="card-text">
                    <span class="text-muted"><%= message.user.name %> at <%= message.timestamp %> says</span><br>
                    <%= message.body %>
                </p>
            </div>
        </div>
    </div>
</div>

app/views/private_chat_rooms/_private_chat_room.html.erb
<tr>
    <td><%= link_to "#{private_chat_room.title}", private_chat_room_path(private_chat_room) %></td>
</tr>

app/views/private_chat_rooms/index.html.erb
<%= link_to "Back to Home", chat_rooms_path %>
<div class="row">
    <div class="col-sm-6">
        <h4>Private Chat Rooms</h4>

        <table>
            <%= render @private_chat_rooms %>
        </table>
    </div>
</div>

app/views/private_chat_rooms/show.html.erb
<%= link_to "Back to Home", private_chat_rooms_path %>
<% if can_see?(@private_chat_room) %>
    <h1><%= @private_chat_room.title %></h1>

    <div id="private_messages" data-private-chat-room-id="<%= @private_chat_room.id %>">
        <%= render @private_chat_room.private_messages %>
    </div>

    <hr>

    <%= form_for @private_message, url: '#' do |f| %>
        <%= hidden_field_tag 'private_chat_room_id', @private_chat_room.id %>
        <div class="form-group">
            <%= f.text_area :body, class: 'form-control' %>
            <small class="text-muted">From 2 to 1000 characters</small>
        </div>

        <%= f.submit "Post", class: 'btn btn-primary btn-lg' %>
    <% end %>
<% end %>

app/views/private_messages/_private_message.html.erb
<div class="card">
    <div class="card-block">
        <div class="row">
            <div class="col-md-1">
                <%= gravatar_for private_message.user %>
            </div>
            <div class="col-md-11">
                <p class="card-text">
                    <span class="text-muted"><%= private_message.user.name %> at <%= private_message.timestamp %> says</span><br>
                    <%= private_message.body %>
                </p>
            </div>
        </div>
    </div>
</div>